name: Foobar 

on:
 - push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Generate artifact
        run: echo "foobar" > foobar.txt
      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: foobar.txt 
