name: Docker

on:
  push:
    branches: [ workflow ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build Docker Image
        run: make build-image-testy
      - uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/998629990322/locations/global/workloadIdentityPools/cosign/providers/cosign'
          service_account: 'cosigner@jetstack-rob-best.iam.gserviceaccount.com'
      - name: Docker Login
        run: |
          gcloud auth configure-docker
      - name: Push image
        run: make push-image-testy
      # Pass the image ref to the provenance job
      - name: Set the output image ref
        id: output
        run: make output-image-ref-testy
    outputs:
      image_ref: ${{ steps.output.outputs.image_ref }}

  provenance:
    needs: build
    uses: ribbybibby/testy/.github/workflows/provenance.yml@workflow
    secrets:
      COSIGN_GCP_SVC_ACCOUNT: ${{ secrets.COSIGN_GCP_SVC_ACCOUNT }}
    with:
      image_ref: ${{ needs.build.outputs.image_ref }}

