name: Foobar 

on:
 - push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || '' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Foo
        run: echo 'foo'
      - name: Bar
        if: github.ref == 'refs/heads/master'
        run: echo 'bar'
