name: Foobar 

on:
 - push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Foo
        run: echo ${{ secrets.ENV_SECRET }}
      - name: Bar
        if: github.ref == 'refs/heads/master'
        run: echo 'bar'
