name: Docker

on:
  push:
    branches: [ workflow ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build Docker Image
        run: make build-image-testy
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: make push-image-testy
      # Pass the image ref to the provenance job
      - name: Set the output image ref
        id: output
        run: make output-image-ref-testy
    outputs:
      image_ref: ${{ steps.output.outputs.image_ref }}

  provenance:
    needs: build
    uses: ribbybibby/testy/.github/workflows/provenance.yml@master
    with:
      image_ref: ${{ needs.build.outputs.image_ref }}

