name: Foobar 

on:
  push:
    branches:
      - master

jobs:
  promotion:
    name: promotion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Generate artifact
        run: git push origin master:production
