name: Foobar 

on:
  push:
    branches:
      - master

jobs:
  artifact:
    name: artifact 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Generate artifact
        run: echo "foobar" > foobar.txt
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          path: foobar.txt
