on:
  workflow_call:
    secrets:
      COSIGN_GCP_SVC_ACCOUNT:
        required: true
    inputs:
      image_ref:
        required: true
        type: string
env:
  KMS_KEY: "gcpkms://projects/jetstack-rob-best/locations/europe-west1/keyRings/rob-best/cryptoKeys/cosign/versions/1"

jobs:
  generate-provenance:
    name: Generate provenance for image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      # Install cosign
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: v1.4.1

      # Login to the registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.COSIGN_GCP_SVC_ACCOUNT }}

      #- name: Docker Login GCR
      #  run: echo "${COSIGN_GCP_SVC_ACCOUNT}" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
      #  env:
      #    COSIGN_GCP_SVC_ACCOUNT: ${{ secrets.COSIGN_GCP_SVC_ACCOUNT }}

      - name: Sign
        run: |
          cosign sign --key "${{ env.KMS_KEY }}" "${{ inputs.image_ref }}"
