on:
  workflow_call:
    inputs:
      image_ref:
        required: true
        type: string
jobs:
  generate-provenance:
    name: Generate provenance for image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      # Install cosign
      - name: Install cosign
        uses: sigstore/cosign-installer@1e95c1de343b5b0c23352d6417ee3e48d5bcd422

      # Login to the registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Cosign handles figuring out the subject, so just create a mock artifact to
      # operate on. We'll discard the subject field later anyway.
      - name: Create mock artifact
        run: echo "foobar" > mock
      - name: Generate provenance
        uses: philips-labs/SLSA-Provenance-Action@sha256:961312222720166ce5955d075c534f7037de3a7aac72957bb1834ebd5ea68c68
        with:
          artifact_path: mock
          output_path: 'provenance.json'
      - name: Extract predicate
        run: jq '.predicate' provenance.json > predicate.json

      # Attach and sign the attestation
      - name: attach-provenance
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign attest --type slsaprovenance --predicate predicate.json "${{ inputs.image_ref }}"
